version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: files
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  storage:
    build: ./storage
    container_name: storage-service
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=files
      - DB_USER=user
      - DB_PASS=pass
      - PROCESSING_HOST=processing
      - PROCESSING_PORT=8082
      - PORT=8081

  processing:
    build: ./processing
    container_name: processing-service
    depends_on:
      - storage
      - db
    environment:
      - STORAGE_HOST=storage
      - STORAGE_PORT=8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=files
      - DB_USER=user
      - DB_PASS=pass
      - PORT=8082

  gateway:
    build: ./gateway
    container_name: api-gateway
    depends_on:
      - processing
      - storage
    ports:
      - "8080:8080"
    environment:
      - STORAGE_HOST=storage
      - STORAGE_PORT=8081
      - PROCESSING_HOST=processing
      - PROCESSING_PORT=8082
      - PORT=8080

volumes:
  db_data:
